# Standard library imports
import unittest
from os import path, remove

# Third party imports
from flask_testing import TestCase
from flask import jsonify
from xml.etree import ElementTree as ET

# Local app imports
from partyparser import create_app, db
from partyparser.models import CourtCase
from partyparser.helpers import verified_file_type, format_case
from config import TestConfig


class ApiRoutesTests(TestCase):
    """Test suite for JSON API endpoints"""

    def create_app(self):
        return create_app(TestConfig)

    # Setup before each test method
    def setUp(self):
        self.test_file = 'test_file.xml'
        self.uploads_dir = path.join(self.app.root_path, 'uploads')
        self.test_file_path = path.join(self.uploads_dir, self.test_file)
        db.create_all()
        self.seed_db()

    # Cleanup after each test method
    def tearDown(self):
        db.session.remove()
        db.drop_all()
        self.remove_test_xml_files()

    # Helper methods
    def seed_db(self):
        # Seeds test db with two CourtCases
        mock_data = [
            CourtCase(plaintiff='John Doe', defendant='Jane Doe'),
            CourtCase(plaintiff='Frank Zappa', defendant='Eric Clapton')
        ]
        db.session.add_all(mock_data)
        db.session.commit()

    def create_test_xml_file(self):
        # Creates 'test_file.xml' in project root dir
        root = ET.Element('root')
        for x in range(3):
            child = ET.SubElement(root, 'child')
        ET.SubElement(child, 'grandchild').text = 'Some text!'
        tree = ET.ElementTree(root)
        with open(self.test_file, 'w'):
            tree.write(self.test_file)

    def remove_test_xml_files(self):
        # Cleanup xml files generated by tests
        if path.exists(self.test_file):
            # Deletes test_file in project root
            remove(self.test_file)
        if path.isfile(self.test_file_path):
            # Deletes test_file in uploads dir
            remove(self.test_file_path)

    def test_get_to_api_cases(self):
        """Test GET to /api/cases returns all courtcases as JSON"""
        res = self.client.get('/api/cases')
        res_json = res.get_json()
        self.assertEqual(res.status_code, 200,
                         'GET to /api/cases should return 200 status code')
        self.assertEqual(len(res_json), 2)

    def test_get_to_api_cases_id_success(self):
        """Test GET to /api/cases/:id returns single courtcase as JSON"""
        case_id = 2
        db_case = CourtCase.query.get(2)
        formatted_case = format_case(db_case)
        res = self.client.get('/api/cases/{}'.format(case_id))
        res_json = res.get_json()
        self.assertEqual(res.status_code, 200,
                         'GET to /api/cases/:id should return 200 status code')
        self.assertEqual(res_json, formatted_case)

    def test_get_to_api_cases_id_failure(self):
        """Test GET to /api/cases/:id returns 404 if id does not exist"""
        case_id = 100
        res = self.client.get('/api/cases/{}'.format(case_id))
        res_json = res.get_json()
        self.assertEqual(res.status_code, 404)
        self.assertEqual(res_json['message'], 'Case not found.')

    def test_post_to_api_cases_saves_file(self):
        """Test POST to /api/cases with xml payload saves xml on server"""
        self.create_test_xml_file()
        with open(self.test_file) as payload:
            data = {}
            data['file'] = (payload, self.test_file)
            res = self.client.post(
                '/api/cases', content_type='application/xml', data=data)
            self.assertEqual(res.status_code, 201,
                             'Should return 201 status code')
            self.assertTrue(path.isfile(self.test_file_path),
                            'Should save xml file to uploads dir')


if __name__ == '__main__':
    unittest.main(verbosity=2)
