"""empty message

Revision ID: 905656728176
Revises: 
Create Date: 2020-02-23 23:37:44.734877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '905656728176'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courtcase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plaintiff', sa.Text(), nullable=False),
    sa.Column('defendant', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('courtcase')
    # ### end Alembic commands ###
